---
title: "Dive into Python Week 1"
author: "darthaline"
date: "14 Aug 2020"
output:
  html_notebook:
    toc: true
---

# Quiz 1

1. Совместимы ли Python 2 и Python 3?
Несовместимы

2. На каком языке программирования написана основная реализация спецификации Python?
C

3. Какое расширение обычно дают файлам с кодом на Python?
.py

4. Как пишутся комментарии в Python?
# это комментарий

5. Какие имена переменных правильные?
_name
name

6. bool(0.000001) - True или False?
```{python}
bool(0.000001)
```

True

7. Что получится в результате выполнения среза [0:1] для строки "привет"?
"п"
(knitr is lagging with Russian symbols)
```{python}
line = "привет"
line[0:1]
```

8. Какая функция позволяет считать ввод пользователя из терминала?
input()

9. Какой метод превратит байтовую строку в строку?
.decode()

10. Чему будет равен pi_fmt?
```{python}
pi = 3.1415926
pi_fmt = f"{pi:#0.2f}"
pi_fmt
```
Строке "3.14"

11. Предположим, есть пакет foo, в котором находится модуль bar.py, внутри bar.py определена функция с именем run. Какая конструкция импорта является правильной?
from foo.bar import run

12. Предположим, есть код
```{python}
import this
import this
```
Сколько раз напечатаются идиомы Python?
Только единожды

13. Зачем нужен virtualenv (виртуальное окружение)?

Изоляция зависимостей

14. Какая утилита позволяет ставить внешние Python пакеты в систему?

pip

15. Что содержат файлы с расширением .pyc?

Код на Python, cкомпилированный в байткод