---
title: "Dive into Python Week 1"
author: "darthaline"
date: "14 Aug 2020"
output:
  html_notebook:
    toc: true
---

# Practice quiz

1. 10 / 2 – что получится в результате деления?
```{python}
10 / 2
```
Вещественное число 5.0

2. bool(0.0) – True или False?
```{python}
bool(0.0)
```
False

3. Чему равно name?
```{python}
x = 0
y = 12
name = x or y

name
```
12

4. Что выведет print(r"//\\") ?
```{python}
print(r"//\\")
```
//\\

5. Выберите правильные варианты объявления строки в Python?
'строка'
f"строка"
"""строка"""
r"строка"
"строка"

6. Отметьте правдивые факты про строки
строки в Python неизменяемые
строки - это последовательность юникодных символов

7. Что получится в результате выполнения "a"*3 
```{python}
"a"*3 
```
Строка "aaa"

8. Что получится в результате выполнения среза [::-1] для строки “привет”?
```{python}
print("привет"[::-1])
```
“тевирп”

9. Срез [:] строки "привет"
```{python}
print("привет"[:])
```
вернет копию строки "привет"

10. bool("")
```{python}
bool("")
```
False

11. Истинные выражения про байтовые строки
Это последовательность чисел от 0 до 255

12. Какой метод превратит строку в байтовую строку?
encode()

13.Какие из записей не приведут к исключению?
b"test"
b""

14. Что выведет программа с if elif else?
```{python}
x = "Москва"
if "ква" not in x:
  print("1")
elif "ва" not in x:
  print("2")
else:
  print("3")
```
3

15. Что выведет программа?
```{python}
n = 0
while n < 3:
    if n > 0:
        continue
    else:
        break
    n += 1

print(n)
```
0

16. Что выведет программа?
```{python}
s = ""

for i in range(2, 10, 2):
		s += str(i)

print(s)
```
2468
