---
title: "Dive into Python Week 2"
author: "darthaline"
date: "28 Sept 2020"
output:
  html_notebook:
    toc: true
---

# Week 2

```{r}
library(reticulate)
#install_miniconda()
```

## Lists

Lists are ordered sets of items, which can be of different types

```{python}
empty_list = []
empty_list = list()

none_list = [None] * 10

collections = ['list', 'tuple', 'dict', 'set']

user_data = [
    ['Elena', 4.4],
    ['Andrey', 4.2]
]

type(user_data)
```

To get the length of the list we can use function `len`

```{python}
len(collections)
```

To get an elelemet of the list we can use it's index. 0 directs to the first element, -1 to the last

```{python}
print(collections)

print(collections[0])
print(collections[-1])
```

We can also change the the elements by referring to them by the index:

```{python}
collections[3] = 'frozenset'
print(collections)
```

To check whether the object is in the list we can use `in`

```{python}
'tuple' in collections
```

We can subset the lists:

```{python}
range_list = list(range(10))
print(range_list)

range_list[1:3] # one to three
range_list[3:] # after #3
range_list[:5] # before #5
range_list[::2] # each second element (starting from #1)
range_list[::-1] # reverse order
range_list[1::2] # every second starting from #1
range_list[5:1:-1] # reverse from #5 to #1
```

Important to note that subsetting creates a new object different from original list

```{python}

range_list[:] is range_list
```

We can iterate through lists:

```{python}
collections = ['list', 'tuple', 'dict', 'set']

for collection in collections:
    print('Learning {}...'.format(collection))
```

To get the index number we can use `enumerate`

```{python}
for idx, collection in enumerate(collections):
    print('#{} {}'.format(idx, collection))
```

Adding elements to the list:

```{python}
collections.append('OrderedDict')
print(collections)
collections.extend(['ponyset', 'unicorndict'])
print(collections)
collections += [None]
print(collections)
```

Deleting element from the list:

```{python}
del collections[4]
print(collections)
```

Math functions for lists:

```{python}
numbers = [4, 17, 19, 9, 2, 6, 10, 13]

print(min(numbers))
print(max(numbers))
print(sum(numbers))
```

Changing list into a string:

```{python}
tag_list = ['python', 'course', 'coursera']
print(', '.join(tag_list))
```

Making a list of random elements. underscore in the for cycle means we don't care for the iteratable variable:

```{python}
import random

numbers = []
for _ in range(10):
    numbers.append(random.randint(1, 20))
    
print(numbers)
```

Sorting elements. `sorted` creates a new list:

```{python}
print(sorted(numbers))
print(sorted(numbers, reverse=True))
print(numbers)
```

`sort` changes the contents of the original list:

```{python}
numbers.sort()
print(numbers)

numbers.sort(reverse=True)
print(numbers)
```

`reversed` creates an iterator function:

```{python}
print(reversed(numbers))
print(list(reversed(numbers)))
```

## Tuple (Кортеж)

```{python}
empty_tuple = ()
empty_tuple = tuple()
type(empty_tuple)
```
Tuples are immutable:

```{python}
immutables = (int, str, tuple)
immutables[0] = float
```

But the elements inside them can be changed:

```{python}
blink = ([], [])
blink[0].append(0)
print(blink)
```

They can also be hashed

```{python}
hash(tuple())
```

Should be careful with single element tuples, since w/o a comma it's just interpreted as a type of the element

```{python}
one_element_tuple = (1,)
guess_what = (1)

type(guess_what)
```


## Functions

Basic function definition

```{python}
def get_seconds():
    """Documentation: Return current seconds"""
    from datetime import datetime
    return datetime.now().second #shows what value to return. without one by default would return None
    
get_seconds() # to call function
get_seconds.__doc__ # to get function documentation
get_seconds.__name__ #to get function name
```

Function with parameters

```{python}
def split_tags(tag_string):
    tag_list = []
    for tag in tag_string.split(','):
        tag_list.append(tag.strip())
    
    return tag_list


split_tags('python, coursera, mooc') #without input parameters would give an error
```

Type annotation is possible in Python:

```{python}
def add(x: int, y: int) -> int:
    return x + y


print(add(10, 11))
print(add('still ', 'works'))
```
However using other types won't cause an error, example with strings still works.

There are two ways to pass value, through link or through direct value.

This example passes the link to an object and thus `values` changes:

```{python}
def extender(source_list, extend_list):
    source_list.extend(extend_list)
    

values = [1, 2, 3]
extender(values, [4, 5, 6])

print(values)
```

This example passes the values, because tuple types cannot be changed:

```{python}
def replacer(source_tuple, replace_with):
    source_tuple = replace_with
    

user_info = ('Guido', '31/01')
replacer(user_info, ('Larry', '27/09'))

print(user_info)
```

Overall, it's best to avoid changing global variables within a function, because change is often not obvious, it's confusing to other programmers.

It's possible to use named arguments when caling a function.

```{python}
def say(greeting, name):
    print('{} {}!'.format(greeting, name))
    

say('Hello', 'Kitty')
say(name='Kitty', greeting='Hello')
```

Each function has an area of visibility:

```{python, echo=FALSE}
result = 0

def increment():
    result += 1
    return result

print(increment())
```

Here we're getting an error because result is a global variable

It's possible to use default arguments:

```{python}
def greeting(name='it\'s me...'):
    print('Hello, {}'.format(name))
    
    
greeting()
```

We should be careful with default values when they are changable: here calling `append_one()` two times in a row changes the default value:

```{python}
def append_one(iterable=[]):
    iterable.append(1)
    return iterable


print(append_one([1]))
print(append_one.__defaults__)
print(append_one())
print(append_one.__defaults__)
print(append_one())
print(append_one.__defaults__)
```
To avoid this we can set the default to `None`, which can be done in 2 ways:

```{python}
def function(iterable=None):
    if iterable is None:
        iterable = []
    

def function(iterable=None):
    iterable = iterable or []
```


We can define a function which has a varied number of input parameters using *

```{python}
def printer(*args):
    print(type(args))
    
    for argument in args:
        print(argument)


printer(1, 2, 3, 4, 5)

name_list = ['John', 'Bill', 'Amy']
printer(*name_list)
```

Similarly we can work with dictionaries

```{python}
def printer(**kwargs):
    print(type(kwargs))
    
    for key, value in kwargs.items():
        print('{}: {}'.format(key, value))
        
        
printer(a=10, b=11)
```
Two stars during the function call would make the first argument to be `user_id`, and second `feedback`
```{python}
payload = {
    'user_id': 117,
    'feedback': {
        'subject': 'Registration fields',
        'message': 'There is no country for old men'
    }
}

printer(**payload)
```

## Files

```{python}
f = open('filename.txt')

text_modes = ['r', 'w', 'a', 'r+'] #read, write, add, read+write
binary_modes = ['br', 'bw', 'ba', 'br+'] #corresponding byte

f = open('filename.txt', 'w')

f.write('The world is changed.\nI taste it in the water.\n')

f.close()
```
When we read second time, we don't get anything because the read pointer is already at the end of the file.
```{python}
f = open('filename.txt', 'r+')
f.read()
f.tell()
f.read()
```
To read the file again we need to use method `seek()` to get back to start of the file
```{python}
f.seek(0)
f.tell()
print(f.read())
f.close()
```

Method `readline()` allows to read one string at a time:

```{python}
f = open('filename.txt', 'r+')
f.readline()
f.close()
```

Method `readlines()` returns a list of strings:

```{python}
f = open('filename.txt', 'r+')
f.readlines()
f.close()

#f.read() # reading a file after closing would give an error
```

To avoid the opening/closing hassle one could use a context manager

```{python}
with open('filename') as f:
    print(f.read())
```

## Functional programming

Functions are objects, and we can pass functions to other functions, and call functions from those functions. Here we defined a function `caller()` which calls function `func` with parameters `param` which we passed. We use caller to call function printer:

```{python}
def caller(func, params):
    return func(*params)


def printer(name, origin):
    print('I\'m {} of {}!'.format(name, origin))
    
    
caller(printer, ['Moana', 'Motunui'])
```

It's also possible to define functions within other functions:

```{python}
def get_multiplier():
    def inner(a, b):
        return a * b
    return inner
    
    
multiplier = get_multiplier()
multiplier(10, 11)

print(multiplier.__name__)
```
Importantly the name of multiplier is inner, since that's the function which actually returns the value.

Here we define multiplier function which would multiply the passed number by the number we passed it originally. This is called замыкание.

```{python}
def get_multiplier(number):
    def inner(a):
        return a * number
    return inner

multiplier_by_2 = get_multiplier(2)
multiplier_by_2(10)
```
There are some helpful functions for the cases when we need to pass a function to other functions.

Here function `map` applies function `squarify` over all values of `range(5)`.

```{python}
def squarify(a):
    return a ** 2


list(map(squarify, range(5)))
```
We're calling list around map, because by default it returns a map object, which is it's own internal thing, and we'd rather not deal with it.

This code is equivalent to use of cycle `for`, but it's much simpler and cleaner with `map`:

```{python}
squared_list = []

for number in range(5):
    squared_list.append(squarify(number))
    
print(squared_list)
```

Another function which is used with other functions is `filter`, which filter the values in an iterable object based on a predictor:

```{python}
def is_positive(a):
    return a > 0


list(filter(is_positive, range(-2, 3)))
```

This code is equivalent to use of cycle `for`, but it's much simpler and cleaner with `filter`:

```{python}
positive_list = []

for number in range(-2, 3):
    if is_positive(number):
        positive_list.append(number)
        
print(positive_list)
```

In cases where we don't need to reuse the function, we can use anonymous (or lambda) functions:

```{python}
list(map(lambda x: x ** 2, range(5)))

type(lambda x: x ** 2)

list(filter(lambda x: x > 0, range(-2, 3)))
```

### Function: list of numbers to list of strings

```{python}
def numbers_to_strings(number_list):
    return list(map(str, number_list))
    
numbers_to_strings([1, 0, -5.6, 1000.1])
```

Pacage `functools` has several other useful functions. For example, function `reduce` which accepts the function and an iterable object, and it iterates over them, by applying the results of the previous iteration to the next value in the iterable object.


```{python}
from functools import reduce


def multiply(a, b):
    return a * b

reduce(multiply, [1, 2, 3, 4, 5])
```

It's similarly possible to apply it to lambda functions:

```{python}
reduce(lambda x, y: x * y, range(1, 6))
```

Another useful function is `partial`, which takes a function and a parameter, and creates a new function with a default value equal to that parameter.

```{python}
from functools import partial


def greeter(person, greeting):
    return '{}, {}!'.format(greeting, person)


hier = partial(greeter, greeting='Hi')
helloer = partial(greeter, greeting='Hello')


print(hier('brother'))
print(helloer('sir'))
```
Previosly when working with lists we would do smth like this:

```{python}
square_list = []
for number in range(10):
    square_list.append(number ** 2)
print(square_list)
```

There's a better way in Python to create list exressions - list comprehensions: 

```{python}
square_list = [number ** 2 for number in range(10)]
print(square_list)
```

Similarly we can use list comprehensions with a condition. Previously:

```{python}
even_list = []
for number in range(10):
    if number % 2 == 0:
        even_list.append(number)
print(even_list)
```

And with list comprehensions:

```{python}
even_list = [num for num in range(10) if num % 2 == 0]
print(even_list)
```

Similarly we can define dictionaries:

```{python}
square_map = {number: number ** 2 for number in range(5)}
print(square_map)
```

and sets:

```{python}
reminders_set = {num % 10 for num in range(100)}
print(reminders_set)
```

the expression we use to generate those has a type:

```{python}
print(type(number ** 2 for number in range(5)))
```

Finally, function `zip` is also commonly used and allows to stick together two iterable objects:

```{python}
num_list = range(7)
squared_list = [x ** 2 for x in num_list]

list(zip(num_list, squared_list))
```

```{python}
list(zip(
  filter(bool, range(3)),
  [x for x in range(3) if x]
))
```

## Decorators

Decorators are functions which accept a function and return a function. Simplest decorator just takes in a function and then returns it:

```{python}
def decorator(func):
    return func

@decorator
def decorated():
    print('Hello!')
    
decorated = decorator(decorated)

print(decorated.__name__)
```

It's more interesting when the new function is a modified or an entirely different one:

```{python}
def decorator(func):
    def new_func():
        pass
    return new_func

@decorator
def decorated():
    print('Hello!')
    
decorated()

print(decorated.__name__)
```

Video question:

```{python, echo=FALSE}
def stringify(func):
  return str(func)


@stringify
def multiply(a, b):
  return a * b
  
multiply(10, 2)
```

A decorator which writes the log of the function that was called:

```{python}
import functools

def logger(func):
    @functools.wraps(func)
    def wrapped(*args, **kwargs):
        result = func(*args, **kwargs)
        with open('log.txt', 'w') as f:
            f.write(str(result))

        return result    
    return wrapped

@logger
def summator(num_list):
    return sum(num_list)

print('Summator: {}'.format(summator([1, 2, 3, 4])))

print(summator.__name__)

with open('log.txt', 'r') as f:
    print(f.read())
```
functools wraps allows to keep the name of the function as `summator` rather than `wrapped` for internal consistency/debugging.

Let's write a decorator to write a log into an identified file:

```{python}
def logger(filename):
    def decorator(func):
        def wrapped(*args, **kwargs):
            result = func(*args, **kwargs)
            with open(filename, 'w') as f:
                f.write(str(result))
            return result
        return wrapped
    return decorator

@logger('new_log.txt')
def summator(num_list):
    return sum(num_list)

# summator = logger('log.txt')(summator)

summator([1, 2, 3, 4, 5, 6])

with open('new_log.txt', 'r') as f:
    print(f.read())
```

We can also chain decorators:

```{python}
def first_decorator(func):
    def wrapped():
        print('Inside first_decorator product')
        return func()
    return wrapped

def second_decorator(func):
    def wrapped():
        print('Inside second_decorator product')
        return func()
    return wrapped
    
@first_decorator
@second_decorator
def decorated():
    print('Finally called...')
    
# decorated = first_decorator(second_decorator(decorated))
    
decorated()
```

And another example on chaining decorators:

```{python}
def bold(func):
    def wrapped():
        return "<b>" + func() + "</b>"
    return wrapped


def italic(func):
    def wrapped():
        return "<i>" + func() + "</i>"
    return wrapped


@bold
@italic
def hello():
    return "hello world"


# hello = bold(italic(hello))


print(hello())
```

## Generators

Generator functions have `yield` in them. `yield` is similar in action to return, however the function doesn't exit.

```{python}
def even_range(start, end):
    current = start
    while current < end:
        yield current
        current += 2
        
for number in even_range(0, 10):
    print(number)
```

We can observe this using `next`

```{python}
ranger = even_range(0, 4)

next(ranger)
next(ranger)
next(ranger) # condition stops working so we get stop iteration.
```


```{python}
def list_generator(list_obj):
    for item in list_obj:
        yield item
        print('After yielding {}'.format(item))


generator = list_generator([1, 2, 3])
print(generator)

next(generator)
next(generator)
next(generator)
next(generator)

```

We only get 2 "After yielding", because the function is interrupted after `yield`.

Generator functions allow to remember where the function left of and continue from there. `range` is a generator, and instead of loading all the numbers into memory, it calls for a new one when needed.

One classical example of generators is fibbonacci numbers:

```{python}
def fibonacci(number):
    a = b = 1
    for _ in range(number):
        yield a
        a, b = b, a + b
        
for num in fibonacci(10):
    print(num)
```

Generators are also able to receive values, using generator method `send`.

```{python}
def accumulator():
    total = 0
    while True:
        value = yield total
        print('Got: {}'.format(value))

        if not value: break
        total += value

generator = accumulator()

next(generator)

print('Accumulated: {}'.format(generator.send(1)))
print('Accumulated: {}'.format(generator.send(1)))
print('Accumulated: {}'.format(generator.send(1)))

next(generator)
```

