---
title: "Dive into Python Week 3"
author: "darthaline"
date: "28 Sept 2020"
output:
  html_notebook:
    toc: true
---

# Week 3
```{r}
library(reticulate)
```

## Classes

Data types we've learned about previously are classes in python.

We can use `type` to check the class of an object:

```{python}
num = 13.0
print(type(num))
```

### `isinstance` function

Function `isinstance` allows to check if the object belongs to a certain class:

```{python}
num = 13
isinstance(num, int)

numbers = {}
isinstance(numbers, dict)
```

We can define class as follows:

```{python}
class Human:
    pass #does nothing
#or
class Robot:
    """This class allows to make robots""" #documentation

print(Robot)

print(dir(Robot))
```

Even newly created classes have quite a few pre-defined methods.

Let's create a class `Planet`, and an object of this class `planet`

```{python}
class Planet:
    pass
    
planet = Planet()
print(planet)
```

We can create a list of `Planet` class objectS:

```{python}
solar_system = []
for i in range(8):
    planet = Planet()
    solar_system.append(planet)

print(solar_system) 
```

Class instances are hashable, so we can use them as keys in a dictionary:

```{python}
solar_system = {}
for i in range(8):
    planet = Planet()
    solar_system[planet] = True

print(solar_system)
```

The way we've defined the objects in the list means that none of the planets have their own names/specific properties. We can redefine those using method `__init__`:

```{python}
class Planet:
    def __init__(self, name):
        self.name = name

earth = Planet("Earth")
print(earth.name)
print(earth)

```

To make `print` of the class object more meaningful we can redefine method `__str__`

```{python}
class Planet:
    def __init__(self, name):
        self.name = name
    def __str__(self):
        return self.name


earth = Planet("Earth")
print(earth)
```

So now we can apply that to a list:

```{python}
solar_system = []

planet_names = [
    "Mercury", "Venus", "Earth", "Mars", 
    "Jupiter", "Saturn", "Uranus", "Neptune"
]

for name in planet_names:
    planet = Planet(name)
    solar_system.append(planet)

print(solar_system)
```

Unfortunately defining them in a list invokes another method __repr__. To fix this we can do the following:

```{python}
class Planet:
    
    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return f"Planet {self.name}"
        
solar_system = []

planet_names = [
    "Mercury", "Venus", "Earth", "Mars", 
    "Jupiter", "Saturn", "Uranus", "Neptune"
]

for name in planet_names:
    planet = Planet(name)
    solar_system.append(planet)

print(solar_system)
```

### Class attributes

We can also modify the attributes of a class:

```{python}
mars = Planet("Mars")
print(mars)

mars.name

mars.name = "Second Earth?"
mars.name
```

If the attribute doesn't exist, we'll get an error:
```{python}
mars.mass
```

Similar thing would happen if we delete the attribute and then refer to it:

```{python}
del mars.name

mars.name
```

We can define class attributes, which are variables belonging to the class itself, rather than to its objects:

```{python}
class Planet:
    count = 0
    def __init__(self, name, population=None):
        self.name = name
        self.population = population or []
        Planet.count += 1
earth = Planet("Earth")
mars = Planet("Mars")

print(Planet.count)
mars.count
```

### Class destructor

Method __del__ is a destructor of the class, and we can redefine it, however it's best to avoid it, and use other methods.

```{python}
class Human:

    def __del__(self):
        print("Goodbye!")

human = Human()
del human
```

### Class dictionary

We can call a dictionary of a class by using method `__dict__` on the object:

```{python}
class Planet:
    """This class describes planets"""
    
    count = 1
    
    def __init__(self, name, population=None):
        self.name = name
        self.population = population or []


planet = Planet("Earth")
planet.__dict__

planet.mass = 5.97e24
planet.__dict__
```

Similarly we can get a dict of the class itself.

```{python}
Planet.__dict__
```

We can call class documentation either through the object or a class itself:

```{python}
Planet.__doc__
planet.__doc__
```

To get the class from the object we can use method `__class__`

```{python}
planet.__class__
```

### Class constructor

Method `__new__` is a constructor of the class object. Here we redefine `__new__` and `__init__` to give us messages indicating when they are called:

```{python}
class Planet:

    def __new__(cls, *args, **kwargs):
        print("__new__ called")
        obj = super().__new__(cls)
        return obj

    def __init__(self, name):
        print("__init__ called")
        self.name = name
        
earth = Planet("Earth")
```

When we called Planet("Earth"), it called function new, which checked that the object being created is of the right type, and then called `__init__`

### Methods

Methods are simply functions in the context of a specific class.

```{python}
#class definitions
class Human:

    def __init__(self, name, age=0):
        self.name = name
        self.age = age

class Planet:

    def __init__(self, name, population=None):
        self.name = name
        self.population = population or []
 
    def add_human(self, human):
        print(f"Welcome to {self.name}, {human.name}!")
        self.population.append(human)

#creating objects
mars = Planet("Mars")
bob = Human("Bob")

#calling method add human
mars.add_human(bob)
print(mars.population)
```

We can call a method from another method.

```{python}
class Human:
    def __init__(self, name, age=0):
        self._name = name
        self._age = age
 
    def _say(self, text):
        print(text)
 
    def say_name(self):
        self._say(f"Hello, I am {self._name}")
 
    def say_how_old(self):
        self._say(f"I am {self._age} years old")

bob = Human("Bob", age=29)

bob.say_name()
bob.say_how_old()
```
Important to note that python doesn't have private methods/variables, and everything is accessible, so there is a convention that underscore methods/variables such as `_say` or `_name` are not recommended for use and can be removed, or their functionality chan be changed quite drastically.

```{python}
print(bob._name)

bob._say("Whatever we want")
```

Class methods are the methods which work not just on a single instance but on the entire class.

```{python}
class Event:
 
    def __init__(self, description, event_date):
        self.description = description
        self.date = event_date

    def __str__(self):
        return f"Event \"{self.description}\" at {self.date}"

from datetime import date

event_description = "Explain what is @classmethod"
event_date = date.today()

event = Event(event_description, event_date)
print(event)
```

A lot of modern messenger services have smart assistance who accept messages and add various events to the calender. We could try to make one ourselves. Admittedly parsing the input is a non-trivial task which normally would require external libraries or services. in our case we are just doing it as a simple example. Method `from_string` comes with a @classmethod decorator, which makes it a class method. unlike other methods, class method first accepts the class itself as `cls`. this way classmethod can be used as an alternative constructor for the class.

```{python}
def extract_description(user_string):
    return "opening of world footbal cup"

def extract_date(user_string):
    return date(2018, 6, 14)

class Event:
 
    def __init__(self, description, event_date):
        self.description = description
        self.date = event_date
    
    def __str__(self):
        return f"Event \"{self.description}\" at {self.date}"

    @classmethod
    def from_string(cls, user_input):
        description = extract_description(user_input)
        date = extract_date(user_input)
        return cls(description, date)

event = Event.from_string("add to my calendar opening of world footbal cup for 14th of july 2018")
print(event)
```

Internal classes use class methods also:

```{python}
dict.fromkeys("12345")
```